# Numpy_Assignment_2::

## Question:1

### Convert a 1D array to a 2D array with 2 rows?

#### Desired output::

array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [8]:
import numpy as np

a = np.arange(10)
a.reshape(2,5)


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

## Question:2

###  How to stack two arrays vertically?

#### Desired Output::

In [10]:
a = np.array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
b = np.array      ([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])


np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

## Question:3

### How to stack two arrays horizontally?

#### Desired Output::

In [13]:
a = np.array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1]])
b =     np.array([[5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1, 5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

## Question:4

### How to convert an array of arrays into a flat 1d array?

#### Desired Output::

In [14]:
a = np.array([[1,2,4],[3,6,7]])
a.flatten()

array([1, 2, 4, 3, 6, 7])

## Question:5

### How to Convert higher dimension into one dimension?

#### Desired Output::

In [15]:
a = np.arange(15).reshape(5,3)
a.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

## Question:6

### Convert one dimension to higher dimension?

#### Desired Output::

In [17]:
a = np.arange(15).reshape(5,3)
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

## Question:7

### Create 5x5 an array and find the square of an array?

In [19]:
a = np.arange(25).reshape(5,5)
np.square(a)

array([[  0,   1,   4,   9,  16],
       [ 25,  36,  49,  64,  81],
       [100, 121, 144, 169, 196],
       [225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576]], dtype=int32)

## Question:8

### Create 5x6 an array and find the mean?

In [21]:
b = np.arange(30).reshape(5,6)
np.mean(b)

14.5

## Question:9

### Find the standard deviation of the previous array in Q8?

In [22]:
np.std(b)

8.65544144839919

## Question:10

### Find the median of the previous array in Q8?

In [24]:
np.median(b)

14.5

## Question:11

### Find the transpose of the previous array in Q8?

In [25]:
np.transpose(b)

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

## Question:12

### Create a 4x4 an array and find the sum of diagonal elements?

In [27]:
t = np.arange(16).reshape(4,4)
print(a,np.trace(t))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]] 30


## Question:13

### Find the determinant of the previous array in Q12?

In [29]:
np.linalg.det(t)

-2.9582283945787796e-30

## Question:14

### Find the 5th and 95th percentile of an array?

## Question:15

### How to find if a given array has any null values?

In [31]:
a = np.arange(10)
np.isnan(a)

array([False, False, False, False, False, False, False, False, False,
       False])