# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [3]:
import numpy as np

2. Create a null vector of size 10 

In [130]:
a = np.empty(10)

3. Create a vector with values ranging from 10 to 49

In [131]:
b = np.arange(10,50)

4. Find the shape of previous array in question 3

In [132]:
b.shape

(40,)

5. Print the type of the previous array in question 3

In [133]:
b.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [134]:
print((np.__version__))
print(np.show_config())

1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Wajahat/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/Wajahat/Anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/Wajahat/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows

7. Print the dimension of the array in question 3


In [135]:
b.ndim

1

8. Create a boolean array with all the True values

In [136]:
c = np.full(10,True)
d = np.ones((3,4), dtype = bool)
c
d

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

9. Create a two dimensional array




In [137]:
e = np.array([[1,2,3],[4,3,5], [5,7,8]])
e

array([[1, 2, 3],
       [4, 3, 5],
       [5, 7, 8]])

10. Create a three dimensional array



In [138]:
f = np.ones((3,3,3))
g = np.array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])
print(f)
print(g)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]


Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [139]:
reverse = np.array([1,2,3,4,5])
reverse[::-1]

array([5, 4, 3, 2, 1])

12. Create a null vector of size 10 but the fifth value which is 1 

In [140]:
null_vector = np.empty(10)
null_vector[4] = 1
print(null_vector)

[0. 1. 2. 3. 1. 5. 6. 7. 8. 9.]


13. Create a 3x3 identity matrix

In [141]:
idn = np.identity(3)
idn

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [142]:
arr = np.array([1, 2, 3, 4, 5])
arr.astype('float32')

array([1., 2., 3., 4., 5.], dtype=float32)

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [143]:
arr1 = np.array([[1., 2., 3.],

            [4., 5., 6.]])  
arr2 = np.array([[0., 4., 1.],

           [7., 2., 12.]])

multiplication = np.matmul(arr1,arr2.reshape((3,2)))
multiplication

array([[  8.,  54.],
       [ 17., 123.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [144]:
ans = arr1 == arr2
ans

array([[False, False, False],
       [False, False, False]])

17. Extract all odd numbers from arr with values(0-9)

In [147]:
arr = np.arange(10, dtype = 'i4')
arr2 = []
for i in arr:
    if (i%2) != 0:
        arr2.append(i)
        
arr3 = np.array(arr2)
arr3

array([1, 3, 5, 7, 9])

18. Replace all odd numbers to -1 from previous array

In [156]:
arr = np.arange(10, dtype = 'i4')

for i in arr:
    if (i%2) != 0:
        arr[i] = -1
        
        
arr


array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [161]:
arr = np.arange(10)
arr[[5,6,7,8]] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [168]:
array = np.ones((4,4))
array[:,1:-1] = 0
array

array([[1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.],
       [1., 0., 0., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [171]:
arr2d = np.array([[1, 2, 3],

            [4, 5, 6], 

            [7, 8, 9]])
arr2d[1][1] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

---
Convert all the values of 1st array to 64


In [176]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
arr3d[:][:][0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first 1st 1-D array from it

In [185]:
array = np.arange(10).reshape(5,2)
array[0:1, 0:2]

array([[0, 1]])

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [7]:
array = np.arange(10).reshape(5,2)
array[1,1]


3

25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [13]:
array = np.arange(10).reshape(2,5)
array[:,-2]


array([3, 8])

26. Create a 10x10 array with random values and find the minimum and maximum values

In [13]:
A = np.random.rand(10,10)
minimum = np.amin(A)
maximum = np.amax(A)
print(maximum, minimum)

0.9929055918630306 0.013102076657465878


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [15]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.intersect1d(a,b)

array([2, 4])

28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [19]:
a = np.array([1,2,3,2,3,4,3,4,5,6]) 
b = np.array([7,2,10,2,7,4,9,4,9,8])
ans = []
for i in range(len(a)):
    if a[i] == b[i]:
        ans.append(i)
ans_np = np.array(ans)   
ans_np

array([1, 3, 5, 7])

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [20]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) 
data = np.random.randn(7, 4)
data

array([[-1.36339077,  1.18876724,  0.24048148,  2.50561533],
       [ 0.81037899, -0.05978365, -0.24590395, -0.30888585],
       [-0.67011933,  1.43636912,  1.33917107, -0.49657317],
       [-0.55738227, -0.02262179, -0.63212419, -0.17538627],
       [-1.04215281,  0.51770632,  0.54622778, -1.65141046],
       [-0.13316037, -0.01060314, -1.47578845,  0.69011192],
       [-0.33837778, -0.97256085,  0.69616386, -1.06621161]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [24]:
a = np.arange(1,16).reshape(5,3)
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [26]:
a = np.arange(1,17).reshape(2,2,4)
a

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12],
        [13, 14, 15, 16]]])

33. Swap axes of the array you created in Question 32

In [30]:
np.swapaxes(a,0,1)

array([[[ 1,  2,  3,  4],
        [ 9, 10, 11, 12]],

       [[ 5,  6,  7,  8],
        [13, 14, 15, 16]]])

34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [36]:
a = np.arange(11)
b = []
for i in a:
    if i > 0.5:
        b.append(i**2) 
        
b = np.array(b)
b

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [ ]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
names[names]

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b



In [5]:
a = np.array([1,2,3,4,5]) 
b = np.array([5,6,7,8,9])
np.setdiff1d(b,a)

array([6, 7, 8, 9])

38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [12]:
sampleArray = np.array([[34,43,73],[82,22,12],[53,94,66]])
sampleArray[:,1] = [10,10,10]
sampleArray

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [13]:
x = np.array([[1., 2., 3.], [4., 5., 6.]]) 
y = np.array([[6., 23.], [-1, 7], [8, 9]])
np.dot(x,y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [16]:
a = np.arange(20).reshape(4,5)
np.cumsum(a)

array([  0,   1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,
        91, 105, 120, 136, 153, 171, 190], dtype=int32)